name: clement
on:
    push:
        branches: [main]

jobs:
    job2:
        runs-on: ubutunu-latest
        steps:
            - name : ububu
              run: echo "googoo sgaga"
    job1:
        runs-on: windows-latest
        needs: [job2]
        steps:
            - name: My awesome step
              run: mkdir app

            - name: my other awesome step
              run: dir
                