name: clement
on:
    push:
        branches: [main]

jobs:
    job1:
        runs-on: windows-latest
        steps:
            - name: My awesome step
              run: mkdir app

            - name: my other awesome step
              run: dir
                
