name: clement
on:
    #push:
        #branches: [main]
    workflow_dispatch

jobs:
    job2:
        runs-on: ubuntu-latest
        steps:
            - name : ububu
              run: echo "googoo gaga"
    job1:
        runs-on: windows-latest
        needs: [job2]
        steps:
            - name: My awesome step
              run: mkdir app

            - name: my other awesome step
              run: dir
                